#!bin/bash

print_separator() {
    echo -e "########################################################################################"
}

print_separator
print_separator
echo -e "GitOps Installation"
print_separator
print_separator

echo -e "Installing gitops workshop resources"
oc apply -k gitops/operator
sleep 15;

oc apply -k gitops/workspace
sleep 2;
oc apply -k application;


print_separator
print_separator
echo -e "CICD Installation"
print_separator
print_separator

print_separator
echo -e "Installing operators\n"
oc apply -k cicd/operator
sleep 15;

print_separator
echo -e "Generating sealed secret for quay credentials\n"
kubeseal --scope cluster-wide -o yaml < cicd/workspace/quay-credentials-generic-secret.yaml  > cicd/workspace/quay-credentials-sealed-secret.yaml

print_separator
echo -e "Create pro-shop project"
oc new-project pro-shop

print_separator
echo -e "Installing workshop cicd resources\n"
oc apply -k cicd/workspace
oc apply -k cicd/pipeline
sleep 5;
oc apply -k cicd/trigger

# Remove files generated by script
rm cicd/workspace/quay-credentials-sealed-secret.yaml