#!bin/bash

print_separator() {
    echo -e "########################################################################################"
}

print_separator
echo -e "Installing operators\n"
oc apply -k cicd/operator

print_separator
echo -e "Generating sealed secret for quay credentials\n"
kubeseal --scope cluster-wide -o yaml < cicd/workspace/quay-credentials-generic-secret.yaml  > cicd/workspace/quay-credentials-sealed-secret.yaml

print_separator
echo -e "Create pro-shop project"
oc new-project pro-shop

print_separator
echo -e "Installing workshop resources\n"
oc apply -k cicd/workspace
oc apply -k cicd/pipeline
oc apply -k cicd/trigger

# Remove files generated by script
rm cicd/workspace/quay-credentials-sealed-secret.yaml