apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-ci
spec:
  workspaces:
    - name: source
    - name: scratch
  params:
    - name: url
      description: Git repository url
    - name: branch
      description: Revision to use
    - name: image-name
      description: Image name
    - name: image-url
      description: Container image URL to publish
  tasks:
  - name: checkout
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
      - name: url
        value: $(params.url)
      - name: revision
        value: $(params.branch)
      - name: deleteExisting
        value: 'true'
    workspaces:
      - name: output
        workspace: source

  - name: test
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - checkout
    params:
      - name: MAVEN_IMAGE
        value: 'maven:3-openjdk-11'
      - name: GOALS
        value: ['clean', 'verify']
    workspaces:
      - name: source
        workspace: source
      - name: maven-settings
        workspace: scratch

  - name: maven-build
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - checkout
    params:
      - name: MAVEN_IMAGE
        value: 'maven:3-openjdk-11'
      - name: GOALS
        value: ['clean', 'package']
    workspaces:
      - name: source
        workspace: source
      - name: maven-settings
        workspace: scratch

  - name: extract-app-version
    taskRef:
      name: extract-version-pom
    runAfter:
      - test
      - maven-build
    params:
      - name: working-dir
        value: .
    workspaces:
      - name: source
        workspace: source

  # - name: add-commitid-to-version
  #   taskRef:
  #     name: add-commitid-to-version
  #   params:
  #     - name: app-version
        # value: $(tasks.extract-app-version.results.app-version)
  #   runAfter:
  #     - extract-app-version
  #   workspaces:
  #     - name: source
  #       workspace: source

  - name: build
    taskRef:
      name: buildah
      kind: ClusterTask
    runAfter: 
      - extract-app-version
    workspaces:
      - name: source
        workspace: source
    params:
      - name: DOCKERFILE
        value: ./src/main/docker/Containerfile
      - name: IMAGE
        value: $(params.image-url):$(tasks.extract-app-version.results.app-version)
      - name: CONTEXT
        value: .
      - name: TLSVERIFY
        value: 'false'
