apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
data:
  password: dGttNTUwNVRLTQ==
  username: amJhcmVh
metadata:
  name: quay-credentials-generic-secret
  annotations:
      tekton.dev/docker-0: quay.io
